export type Category = "strollers" | "car-seats" | "beds" | "walkers" | "accessories";

export type ProductSection = { title: string; items: string[] };

export type Product = {
  slug: string;
  storeId: string;
  title: string;
  name: string;
  group: string;
  category: Category;
  age: string;
  color: string;
  price: string;
  badge: string;
  featured: boolean;
  swatches: string[];
  code: string;
  short: string;
  sections: ProductSection[];
  paragraphs: string[];
  images: string[];
  storeUrl: string;
};

export const categoryOrder: Category[] = ["strollers", "car-seats", "beds", "walkers", "accessories"];

export const categoryMeta: Record<Category, { label: string; description: string }> = {
  strollers: {
    label: "Тэрэг",
    description: "Дан, 2 хос, 3 хос болон хөнгөн аялалын тэрэг — нярайгаас 4 нас хүртэл.",
  },
  "car-seats": {
    label: "Машины суудал",
    description: "Нярайгаас 12 нас хүртэл хэрэглэх 360° эргэдэг, Isofix бэхэлгээтэй суудал.",
  },
  beds: {
    label: "Хүүхдийн манеж",
    description: "Гэрт ч, аялалд ч хялбар эвхэгддэг тоглох, унтах аюулгүй орон зай.",
  },
  walkers: {
    label: "Хөлд оруулагч",
    description: "6 сараас дээш насны хүүхдийн анхны алхмуудад.",
  },
  accessories: {
    label: "Хэрэгсэл",
    description: "Суудлын өндөрлөгч зэрэг өдөр тутмын хэрэгслүүд.",
  },
};

export const groupMeta: Record<string, string> = {
  "3in1": "3-н хос тэрэг (3 in 1)",
  "2in1": "2 хос тэрэг (2 in 1)",
  single: "Дан тэрэг",
  light: "Хөнгөн, аялалын тэрэг",
  carseat: "Машины суудал",
  booster: "Суудлын өндөрлөгч",
  playpen: "Манеж",
  walker: "Хөлд оруулагч",
};

export const products: Product[] = [
  {"slug": "carseat-360", "storeId": "212820/927950", "title": "Машины суудал, 0-12 нас", "name": "Машины суудал 360°", "group": "carseat", "category": "car-seats", "age": "0-12 нас", "color": "", "price": "359,000₮", "badge": "", "featured": true, "swatches": ["#1c1c1c", "#8a8a8a", "#b9a08a"], "code": "", "short": "360 градус эргэдэг, ашиглахад хялбар", "sections": [{"title": "Давуу талууд", "items": ["🧡0-12 нас хүртэл хэрэглэх боломжтой", "🧡Нярайн зөөлөвчтэй", "🧡Аюулгүйн бүстэй", "🧡360 градус эргэдэг тул ашиглахад хялбар", "🧡ISOFIX бэхэлгээний систем", "🧡Суудлын араас бэхлэгч", "🧡Сууудлын бүсээр давхар бэхлэх боломжтой", "🧡Тав тухтай", "🧡Аюулгүй"]}], "paragraphs": [], "images": ["/products/gallery/carseat-360-1.jpg", "/products/gallery/carseat-360-2.jpg", "/products/gallery/carseat-360-3.jpg", "/products/gallery/carseat-360-4.jpg", "/products/gallery/carseat-360-5.jpg"], "storeUrl": "https://bolorhonkids.mn/products/212820/927950"},
  {"slug": "playpen", "storeId": "338494/924706", "title": "Хүүдийн манеж, 0-4 нас", "name": "Хүүхдийн манеж", "group": "playpen", "category": "beds", "age": "0-4 нас", "color": "", "price": "299,000₮", "badge": "", "featured": true, "swatches": ["#9a9a9a"], "code": "PN30", "short": "Бүүвэйлэгч болон хуурайлагчтай", "sections": [{"title": "Онцлог талууд", "items": ["Бүүвэйлдэг хөл", "0-4 нас", "Орны тоглоом", "Нүүрэн тал бууж аав, ээжийн ортой нийлдэг", "Ялаа шумуулны тор", "Хуурайлах тавцан", "Агаарын урсгалыг чөлөөтэй нэвтрүүлэх торон цонх", "Эвхэгддэг", "127*80*65cм"]}], "paragraphs": [], "images": ["/products/gallery/playpen-1.jpg", "/products/gallery/playpen-2.jpg"], "storeUrl": "https://bolorhonkids.mn/products/338494/924706"},
  {"slug": "apollo-pro", "storeId": "116721/899839", "title": "Apollo Pro, 0-12 нас", "name": "Apollo Pro", "group": "carseat", "category": "car-seats", "age": "0-12 нас", "color": "", "price": "589,000₮", "badge": "Шинэ", "featured": true, "swatches": ["#c9b59a", "#1c1c1c"], "code": "", "short": "Бяцхан үрсийнхээ аюулгүй байдалд хариуцлагатай хандаарай! 🧡 Та хүүхдээ машин дотор хамгийн тухтай, аюулгүй байлгахыг хүсэж байна уу? Бидний санал болгож буй 0-12 насны ангилалд тохирох автомашины суудал нь таны гэр бүлийн аялал бүрийг сэтгэл тайван, жаргалтай болгоно", "sections": [], "paragraphs": ["Яагаад заавал энэ суудал гэж?", "✅ Урт хугацааны хөрөнгө оруулалт: 0-12 нас хүртэл буюу нэг суудлыг бүх насанд нь ашиглах боломжтой.", "✅ Дээд зэргийн аюулгүй байдал: ISOFIX бэхэлгээ", "✅ Хялбар бөгөөд ухаалаг: 360 градус эргэдэг тул хүүхдээ суулгах болон авах үед нуруунд ачаалал өгөхгүй.", "✅ Тав тух: Нярайн зөөлөвчтэй, зөөлөн материалаар хийгдсэн нь хол замд ч хүүхдийг таатай мэдрэмжтэй байлгана.", "Таны хүүхдийн аюулгүй байдал — Бидний эрхэм зорилго."], "images": ["/products/gallery/apollo-pro-1.jpg", "/products/gallery/apollo-pro-2.jpg", "/products/gallery/apollo-pro-3.jpg", "/products/gallery/apollo-pro-4.jpg", "/products/gallery/apollo-pro-5.jpg", "/products/gallery/apollo-pro-6.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116721/899839"},
  {"slug": "pc600-grey", "storeId": "116291/899827", "title": "PC600, 3-н хос тэрэг, Grey", "name": "PC600", "group": "3in1", "category": "strollers", "age": "", "color": "Grey", "price": "899,000₮", "badge": "", "featured": true, "swatches": ["#6f6f6f"], "code": "PC600", "short": "Урт хугацааны үнэнч туслах: Нярайгаас эхлээд 4 нас хүртэл нь хэрэглэх ухаалаг хөрөнгө оруулалт.", "sections": [{"title": "", "items": ["👶 Урт хугацааны үнэнч туслах: Нярайгаас эхлээд 4 нас хүртэл нь хэрэглэх ухаалаг хөрөнгө оруулалт.", "🔄 Хоёр тийш харах уян хатан шийдэл: Үрээ өөр рүүгээ харуулж хайрлан ширтэх үү, эсвэл хорвоо ертөнцтэй танилцуулах уу? Аль алинаар нь түрэх боломжтой.", "⏳ Цаг хэмнэх хялбар хураалт: Хамгийн хурдан, хамгийн хялбар хураагдах тул ээжүүд ганцаараа байхдаа ч ямар ч түүртэлгүй ашиглана.", "☁️ Тансаг зөөлөн материал: Арьсанд маш зөөлөн, тухтай мэдрэмж төрүүлэх өндөр зэрэглэлийн даавуу.", "🛌 3 шатлалт налуу: Хүүхдийнхээ хэрэгцээнд тааруулан суугаа, хагас хэвтээ, бүтэн хэвтээ гэсэн 3 байрлалаар тохируулаарай.", "☀️ UPF50+ Нарны хамгаалалт: Хүүхдийн эмзэг арьс, нүдийг нарны хорт туяанаас бүрэн хамгаалах урт сүүдрэвчтэй.", "💎 Тансаг гоёлын хүрээ: Чанартай, удаан эдлэгээтэй бөгөөд таны загварлаг төрхийг улам тодотгох гоёмсог дизайн.", "🧸 Амаржин системийн хамгаалалт: Нэмэлт амаржин (амортизатор) нь зам дагуух доргилтыг хамгийн бага түвшинд барьж, бяцхан үрийг тань гүн нойронд нь саадгүй унтуулна."]}, {"title": "🎁 Та бүх хэрэгцээг нэг дор шийдэх 4-н дагалдах зүйлс", "items": ["🛌 Нярайн ор (Bassinet) – Эхний саруудад хүүхдээ тав тухтай унтуулах өлгий.", "🚗 Машины суудал (Car seat) – Машиндаа ч, тэрэг дээрээ ч шууд суурилуулах аюулгүй шийдэл.", "👶 Үндсэн суудал – Хүүхэд тань томорсон ч хэвтэж, суух үйлдэлтэй тохилог суудал.", "🎒 Mommy bag – Ээжийн болон хүүхдийн бүх хэрэгцээт зүйлсийг багтаах загварлаг, багтаамж ихтэй цүнх."]}], "paragraphs": ["🌿 Яагаад Burbay хүүхдийн тэргийг сонгох хэрэгтэй вэ?"], "images": ["/products/gallery/pc600-grey-1.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/899827"},
  {"slug": "light-stroller-0-3", "storeId": "116291/892409", "title": "Хөнгөн дан тэрэг, 0-3 нас", "name": "Хөнгөн дан тэрэг", "group": "light", "category": "strollers", "age": "0-3 нас", "color": "", "price": "529,000₮", "badge": "", "featured": false, "swatches": ["#6b6b6b"], "code": "", "short": "Аялал болон өдөр тутмын хэрэглээнт нийтсэн нэг гараар хялбар хураагдах бөгөөд маш жижиг хэмжээтэй", "sections": [{"title": "Онцлог талууд", "items": ["Нэг гараар хураагддаг", "Авсаархан, хөнгөн", "Аялал болон өдөр тутмын хэрэглээнд нийцсэн", "Хэвтэж, суух үйлдэлтэй", "4-н дугуйн амаржинтай", "Доороо сагстай", "UPF50+ нарны хаалт"]}], "paragraphs": [], "images": ["/products/gallery/light-stroller-0-3-1.jpg", "/products/gallery/light-stroller-0-3-2.jpg", "/products/gallery/light-stroller-0-3-3.jpg", "/products/gallery/light-stroller-0-3-4.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/892409"},
  {"slug": "single-stroller-0-4", "storeId": "116291/892408", "title": "Хүүхдийн дан тэрэг, 0-4 нас", "name": "Хүүхдийн дан тэрэг", "group": "single", "category": "strollers", "age": "0-4 нас", "color": "", "price": "599,000₮", "badge": "", "featured": false, "swatches": ["#b39b86"], "code": "", "short": "Нэг үйлдэлээр эвхэгдэх боломжтой бөгөөд өдөр тутмын хэрэглээнд төгс нийцсэн", "sections": [{"title": "", "items": ["Нэг үйлдэлээр хураагддаг", "0-4 нас хүртэл ашиглах боломжтой", "Сүүдрэвч сунана", "4-н дугуйн амаржин", "Тав тухтай", "Хэрэглэхэд хялбар", "Хүүхдэд тухтай зөөлөн", "Урд бариул сална", "Утасны халаастай", "Доороо сагстай"]}], "paragraphs": ["Онцлог талууд"], "images": ["/products/gallery/single-stroller-0-4-1.jpg", "/products/gallery/single-stroller-0-4-2.jpg", "/products/gallery/single-stroller-0-4-3.jpg", "/products/gallery/single-stroller-0-4-4.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/892408"},
  {"slug": "booster", "storeId": "116721/881132", "title": "Машины суудлын өндөрлөгч", "name": "Машины суудлын өндөрлөгч", "group": "booster", "category": "accessories", "age": "", "color": "", "price": "79,000₮", "badge": "", "featured": false, "swatches": ["#5a5a5a", "#3a3a3a"], "code": "", "short": "ISOFIX бэхэлгээтэй машины суудлын өндөрлөгч", "sections": [], "paragraphs": [], "images": ["/products/gallery/booster-1.jpg", "/products/gallery/booster-2.jpg", "/products/gallery/booster-3.jpg", "/products/gallery/booster-4.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116721/881132"},
  {"slug": "2in1-stroller", "storeId": "116291/818189", "title": "2 Хос тэрэг, 0-4 нас", "name": "2 хос тэрэг", "group": "2in1", "category": "strollers", "age": "0-4 нас", "color": "", "price": "399,000₮", "badge": "", "featured": false, "swatches": ["#6f6f6f"], "code": "", "short": "Нярай үеэс эхлэн 4-н нас хүртэл ашиглах боломжтой машины суудалтай 2 хос тэрэг", "sections": [{"title": "", "items": ["0-4 нас хүртэл хэрэглэх боломжтой", "4-н дугуйн амортизатор", "Суудал 2 тийш харуулж угсрах боломж", "UPF50+ нарны хаалт", "Сүүдрэвч сунана", "Хэвтэж суух үйлдэлтэй", "Суудлын бүстэй", "Доороо сагстай", "Түрэх бариулны өндөр тохируулах", "Авсаархан, хөнгөн", "Тормоз", "Машины суудал", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/2in1-stroller-1.jpg", "/products/gallery/2in1-stroller-2.jpg", "/products/gallery/2in1-stroller-3.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/818189"},
  {"slug": "reversible-stroller", "storeId": "116291/818143", "title": "Дан тэрэг (Гар шиждэг), 0-4 нас", "name": "Дан тэрэг (гар шилждэг)", "group": "single", "category": "strollers", "age": "0-4 нас", "color": "", "price": "399,000₮", "badge": "", "featured": false, "swatches": ["#b9a08a"], "code": "", "short": "Бүх дугуй 360 градус эргэх боломжтой мөн гар шилждэг мөн хөнгөн авсаархан эвхэгддэг тул өдөр тутмын хэрэглээнд төгс нийцсэн.", "sections": [], "paragraphs": [], "images": ["/products/gallery/reversible-stroller-1.jpg", "/products/gallery/reversible-stroller-2.jpg", "/products/gallery/reversible-stroller-3.jpg", "/products/gallery/reversible-stroller-4.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/818143"},
  {"slug": "j02-grey", "storeId": "116291/817856", "title": "J02, Хүүхдийн 3-н хос тэрэг, Grey", "name": "J02", "group": "3in1", "category": "strollers", "age": "", "color": "Grey", "price": "1,599,000₮", "badge": "Luxury", "featured": true, "swatches": ["#4b4b4b"], "code": "J02", "short": "брэндийн 2026 оны шинэ загвар болох J02 тэрэг нь гоёмсог загвартай, хүүхдэд тухтай тансаг материалтай бөгөөд хүүхдийн хэвтэж, суух түвшин тохируулах гэх мэт давуу талуудыг өөртөө багтаасан мөн нярайн ортойгоо хураагддаг ухаалаг шийдэлтэй", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "Суудал аль ч тийш харсан үед эвхэх боломжтой.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Зөөлөн дугуй нь хүүхдэд тухтай мөн түрэхэд эвтэйхэн мэдрэмж өгнө", "Чанартай, удаан эдлэгээтэй", "Хүүхдийн өндөрт тохируулж сүүдрэвч сунгах", "Хүүхдийн хэвтэх түвшинг 3-н төрлөөр тохируулах", "Нэмэлт зөөлөвчтэй", "Суудлын бүсний түгжээ соронзон", "Нярайн ортойгоо хамт эвхэгддэг"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Нярайн машины суудал", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/j02-grey-1.jpg", "/products/gallery/j02-grey-2.jpg", "/products/gallery/j02-grey-3.jpg", "/products/gallery/j02-grey-4.jpg", "/products/gallery/j02-grey-5.jpg", "/products/gallery/j02-grey-6.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/817856"},
  {"slug": "e83-black", "storeId": "116291/781862", "title": "E83, 2 хос тэрэг, Black", "name": "E83", "group": "2in1", "category": "strollers", "age": "0-4 нас", "color": "Black", "price": "1,399,000₮", "badge": "Бестселлер", "featured": true, "swatches": ["#1c1c1c"], "code": "E83pro", "short": "Хүүхдийн тав тух, аюулгүй байдлыг 100% хангасан мөн хамгийн авсаархан хялбар эвэхэх шийдлийг шингээсэн шилдэг загвар.", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Чанартай, удаан эдлэгээтэй", "Агааржуулах торон цонх"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/e83-black-1.jpg", "/products/gallery/e83-black-2.jpg", "/products/gallery/e83-black-3.jpg", "/products/gallery/e83-black-4.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/781862"},
  {"slug": "e83-ginger", "storeId": "116291/781860", "title": "E83, 2 хос тэрэг, Ginger Brown", "name": "E83", "group": "2in1", "category": "strollers", "age": "0-4 нас", "color": "Ginger Brown", "price": "1,399,000₮", "badge": "", "featured": false, "swatches": ["#6b3f2a"], "code": "E83pro", "short": "Хүүхдийн тав тух, аюулгүй байдлыг 100% хангасан мөн хамгийн авсаархан хялбар эвэхэх шийдлийг шингээсэн шилдэг загвар.", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Чанартай, удаан эдлэгээтэй", "Агааржуулах торон цонх"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/e83-ginger-1.jpg", "/products/gallery/e83-ginger-2.jpg", "/products/gallery/e83-ginger-3.jpg", "/products/gallery/e83-ginger-4.jpg", "/products/gallery/e83-ginger-5.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/781860"},
  {"slug": "e83-iron-grey", "storeId": "116291/774424", "title": "E83, 2 хос тэрэг, Iron Grey", "name": "E83", "group": "2in1", "category": "strollers", "age": "0-4 нас", "color": "Iron Grey", "price": "1,399,000₮", "badge": "", "featured": false, "swatches": ["#5a5a5a"], "code": "E83pro", "short": "Хүүхдийн тав тух, аюулгүй байдлыг 100% хангасан мөн хамгийн авсаархан хялбар эвэхэх шийдлийг шингээсэн шилдэг загвар.", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Чанартай, удаан эдлэгээтэй", "Агааржуулах торон цонх"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/e83-iron-grey-1.jpg", "/products/gallery/e83-iron-grey-2.jpg", "/products/gallery/e83-iron-grey-3.jpg", "/products/gallery/e83-iron-grey-4.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/774424"},
  {"slug": "walker", "storeId": "116724/759387", "title": "Хөлд оруулагч, 6сар+", "name": "Хөлд оруулагч", "group": "walker", "category": "walkers", "age": "6 сар+", "color": "", "price": "159,000₮", "badge": "", "featured": true, "swatches": ["#8c8c8c"], "code": "", "short": "6 сартайгаас 18 сар хүртэл хэрэглэх боломжтой мөн хоолны ширээ болох боломжтой", "sections": [{"title": "Онцлог талууд", "items": ["Эвхэх боломжтой", "Саатуулах боломжтой", "Хоолны ширээ болдог", "Резин дугуйтай", "Хүүхдэд тухтай", "Аюулгүй"]}], "paragraphs": [], "images": ["/products/gallery/walker-1.jpg", "/products/gallery/walker-2.jpg", "/products/gallery/walker-3.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116724/759387"},
  {"slug": "e77-light-grey", "storeId": "116291/753701", "title": "E77, Хүүхдийн 3-н хос тэрэг, Light Grey", "name": "E77", "group": "3in1", "category": "strollers", "age": "", "color": "Light Grey", "price": "1,399,000₮", "badge": "", "featured": true, "swatches": ["#a9a9a9"], "code": "E77LIGHTGREY", "short": "Нярай үеэс эхлэн 4-н нас хүртэл хэрэглэх боломжтой мөн хүүхдэд тухтай зөөлөн, хэрэглэхэд хялбар, машины суудал, хөлийн хучлага, Mom bag-тай гэх мэт олон давуу талуудыг багтаасан", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "Суудал аль ч тийш харсан үед эвхэх боломжтой.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Чанартай, удаан эдлэгээтэй"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Нярайн машины суудал", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/e77-light-grey-1.jpg", "/products/gallery/e77-light-grey-2.jpg", "/products/gallery/e77-light-grey-3.jpg", "/products/gallery/e77-light-grey-4.jpg", "/products/gallery/e77-light-grey-5.jpg", "/products/gallery/e77-light-grey-6.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/753701"},
  {"slug": "e77-dark-grey", "storeId": "116291/753699", "title": "E77, Хүүхдийн 3-н хос тэрэг, Dark Grey", "name": "E77", "group": "3in1", "category": "strollers", "age": "", "color": "Dark Grey", "price": "1,399,000₮", "badge": "", "featured": false, "swatches": ["#4a4a4a"], "code": "E77DARKGREY", "short": "Нярай үеэс эхлэн 4-н нас хүртэл хэрэглэх боломжтой мөн хүүхдэд тухтай зөөлөн, хэрэглэхэд хялбар, машины суудал, хөлийн хучлага, Mom bag-тай гэх мэт олон давуу талуудыг багтаасан", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "Суудал аль ч тийш харсан үед эвхэх боломжтой.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Чанартай, удаан эдлэгээтэй"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Нярайн машины суудал", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/e77-dark-grey-1.jpg", "/products/gallery/e77-dark-grey-2.jpg", "/products/gallery/e77-dark-grey-3.jpg", "/products/gallery/e77-dark-grey-4.jpg", "/products/gallery/e77-dark-grey-5.jpg", "/products/gallery/e77-dark-grey-6.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/753699"},
  {"slug": "pc600-green", "storeId": "116291/748223", "title": "PC600, 3-н хос тэрэг, Green", "name": "PC600", "group": "3in1", "category": "strollers", "age": "", "color": "Green", "price": "899,000₮", "badge": "", "featured": false, "swatches": ["#6f8f7a"], "code": "PC600", "short": "Хүүхдийн тав тух, аюулгүй байдлыг хамгийн дээдээр хангаж, ээж аавуудын цаг зав, хөдөлмөрийг хөнгөвчлөх дэлхийн жишиг дизайн бүхий Burbay олон үйлдэлт тэрэг танд болон таны хүүхдэд төгс мэдрэмжийг бэлэглэнэ. 🤍", "sections": [{"title": "", "items": ["👶 Урт хугацааны үнэнч туслах: Нярайгаас эхлээд 4 нас хүртэл нь хэрэглэх ухаалаг хөрөнгө оруулалт.", "🔄 Хоёр тийш харах уян хатан шийдэл: Үрээ өөр рүүгээ харуулж хайрлан ширтэх үү, эсвэл хорвоо ертөнцтэй танилцуулах уу? Аль алинаар нь түрэх боломжтой.", "⏳ Цаг хэмнэх хялбар хураалт: Хамгийн хурдан, хамгийн хялбар хураагдах тул ээжүүд ганцаараа байхдаа ч ямар ч түүртэлгүй ашиглана.", "☁️ Тансаг зөөлөн материал: Арьсанд маш зөөлөн, тухтай мэдрэмж төрүүлэх өндөр зэрэглэлийн даавуу.", "🛌 3 шатлалт налуу: Хүүхдийнхээ хэрэгцээнд тааруулан суугаа, хагас хэвтээ, бүтэн хэвтээ гэсэн 3 байрлалаар тохируулаарай.", "☀️ UPF50+ Нарны хамгаалалт: Хүүхдийн эмзэг арьс, нүдийг нарны хорт туяанаас бүрэн хамгаалах урт сүүдрэвчтэй.", "💎 Тансаг гоёлын хүрээ: Чанартай, удаан эдлэгээтэй бөгөөд таны загварлаг төрхийг улам тодотгох гоёмсог дизайн.", "🧸 Амаржин системийн хамгаалалт: Нэмэлт амаржин (амортизатор) нь зам дагуух доргилтыг хамгийн бага түвшинд барьж, бяцхан үрийг тань гүн нойронд нь саадгүй унтуулна."]}, {"title": "🎁 Та бүх хэрэгцээг нэг дор шийдэх 4-н дагалдах зүйлс", "items": ["🛌 Нярайн ор (Bassinet) – Эхний саруудад хүүхдээ тав тухтай унтуулах өлгий.", "🚗 Машины суудал (Car seat) – Машиндаа ч, тэрэг дээрээ ч шууд суурилуулах аюулгүй шийдэл.", "👶 Үндсэн суудал – Хүүхэд тань томорсон ч хэвтэж, суух үйлдэлтэй тохилог суудал.", "🎒 Mommy bag – Ээжийн болон хүүхдийн бүх хэрэгцээт зүйлсийг багтаах загварлаг, багтаамж ихтэй цүнх."]}], "paragraphs": ["🌿 Яагаад Burbay хүүхдийн тэргийг сонгох хэрэгтэй вэ?"], "images": ["/products/gallery/pc600-green-1.jpg", "/products/gallery/pc600-green-2.jpg", "/products/gallery/pc600-green-3.jpg", "/products/gallery/pc600-green-4.jpg", "/products/gallery/pc600-green-5.jpg", "/products/gallery/pc600-green-6.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/748223"},
  {"slug": "pc600-khaki", "storeId": "161635/748222", "title": "PC600, 3-н хос тэрэг, Khaki", "name": "PC600", "group": "3in1", "category": "strollers", "age": "", "color": "Khaki", "price": "899,000₮", "badge": "", "featured": false, "swatches": ["#b08c7a"], "code": "PC600", "short": "Хүүхдийн тав тух, аюулгүй байдлыг хамгийн дээдээр хангаж, ээж аавуудын цаг зав, хөдөлмөрийг хөнгөвчлөх дэлхийн жишиг дизайн бүхий Burbay олон үйлдэлт тэрэг танд болон таны хүүхдэд төгс мэдрэмжийг бэлэглэнэ. 🤍", "sections": [{"title": "", "items": ["👶 Урт хугацааны үнэнч туслах: Нярайгаас эхлээд 4 нас хүртэл нь хэрэглэх ухаалаг хөрөнгө оруулалт.", "🔄 Хоёр тийш харах уян хатан шийдэл: Үрээ өөр рүүгээ харуулж хайрлан ширтэх үү, эсвэл хорвоо ертөнцтэй танилцуулах уу? Аль алинаар нь түрэх боломжтой.", "⏳ Цаг хэмнэх хялбар хураалт: Хамгийн хурдан, хамгийн хялбар хураагдах тул ээжүүд ганцаараа байхдаа ч ямар ч түүртэлгүй ашиглана.", "☁️ Тансаг зөөлөн материал: Арьсанд маш зөөлөн, тухтай мэдрэмж төрүүлэх өндөр зэрэглэлийн даавуу.", "🛌 3 шатлалт налуу: Хүүхдийнхээ хэрэгцээнд тааруулан суугаа, хагас хэвтээ, бүтэн хэвтээ гэсэн 3 байрлалаар тохируулаарай.", "☀️ UPF50+ Нарны хамгаалалт: Хүүхдийн эмзэг арьс, нүдийг нарны хорт туяанаас бүрэн хамгаалах урт сүүдрэвчтэй.", "💎 Тансаг гоёлын хүрээ: Чанартай, удаан эдлэгээтэй бөгөөд таны загварлаг төрхийг улам тодотгох гоёмсог дизайн.", "🧸 Амаржин системийн хамгаалалт: Нэмэлт амаржин (амортизатор) нь зам дагуух доргилтыг хамгийн бага түвшинд барьж, бяцхан үрийг тань гүн нойронд нь саадгүй унтуулна."]}, {"title": "🎁 Та бүх хэрэгцээг нэг дор шийдэх 4-н дагалдах зүйлс", "items": ["🛌 Нярайн ор (Bassinet) – Эхний саруудад хүүхдээ тав тухтай унтуулах өлгий.", "🚗 Машины суудал (Car seat) – Машиндаа ч, тэрэг дээрээ ч шууд суурилуулах аюулгүй шийдэл.", "👶 Үндсэн суудал – Хүүхэд тань томорсон ч хэвтэж, суух үйлдэлтэй тохилог суудал.", "🎒 Mommy bag – Ээжийн болон хүүхдийн бүх хэрэгцээт зүйлсийг багтаах загварлаг, багтаамж ихтэй цүнх."]}], "paragraphs": ["🌿 Яагаад Burbay хүүхдийн тэргийг сонгох хэрэгтэй вэ?"], "images": ["/products/gallery/pc600-khaki-1.jpg", "/products/gallery/pc600-khaki-2.jpg", "/products/gallery/pc600-khaki-3.jpg", "/products/gallery/pc600-khaki-4.jpg", "/products/gallery/pc600-khaki-5.jpg", "/products/gallery/pc600-khaki-6.jpg"], "storeUrl": "https://bolorhonkids.mn/products/161635/748222"},
  {"slug": "j01-green", "storeId": "116291/748177", "title": "J01, Luxury 3in1, Green", "name": "J01 Luxury", "group": "3in1", "category": "strollers", "age": "", "color": "Green", "price": "1,599,000₮", "badge": "Luxury", "featured": false, "swatches": ["#4f5d52"], "code": "J01GREEN", "short": "брэндийн 2025 оны шинэ загвар болох J01 тэрэг нь гоёмсог загвартай, хүүхдэд тухтай тансаг материалтай бөгөөд хүүхдийн хэвтэж, суух түвшин тохируулах гэх мэт давуу талуудыг өөртөө багтаасан шилдэг тэрэг юм.", "sections": [{"title": "Онцлог талууд", "items": ["Нярайгаас 4 нас хүртэл хэрэглээ.", "2 тийш харуулж түрэх боломжтой.", "Хамгийн хялбар хураах шийдэл таны цагыг хэмнэнэ.", "Тансаг, зөөлөн, тухтай материал.", "Хэвтэх хүртэл 3-н төрлөөр налуулах боломжтой.", "Гоёлын хүрээ.", "Суудал аль ч тийш харсан үед эвхэх боломжтой.", "UPF50+ халхавч, сүүдрэвч.", "Нэмэлт амаржин нь таны хүүхдэд доргилт бага өгнө.", "Зөөлөн дугуй нь хүүхдэд тухтай мөн түрэхэд эвтэйхэн мэдрэмж өгнө", "Чанартай, удаан эдлэгээтэй", "Хүүхдийн өндөрт тохируулж сүүдрэвч сунгах", "Хүүхдийн хэвтэх түвшинг 3-н төрлөөр тохируулах", "Нэмэлт зөөлөвчтэй", "Суудлын бүсний түгжээ соронзон"]}, {"title": "Дагалдах зүйлс", "items": ["Нярайн ор (bassinet)", "Нярайн машины суудал", "Үндсэн суудал (хэвтэж суух үйлдэлтэй)", "Mommy bag", "Хөлийн хучлага"]}], "paragraphs": [], "images": ["/products/gallery/j01-green-1.jpg", "/products/gallery/j01-green-2.jpg", "/products/gallery/j01-green-3.jpg", "/products/gallery/j01-green-4.jpg", "/products/gallery/j01-green-5.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/748177"},
  {"slug": "light-stroller-0-4", "storeId": "116291/699570", "title": "Хөнгөн тэрэг, 0-4 нас", "name": "Хөнгөн тэрэг", "group": "light", "category": "strollers", "age": "0-4 нас", "color": "", "price": "339,000₮", "badge": "", "featured": false, "swatches": ["#2f6f6a"], "code": "", "short": "Нэг гараар эвхэгдэх боломжтой тул ашиглахад маш хялбар мөн хөлийн хучлагатай, амаржинтай, агаарын солилцоо нэвтрүүлэх торон цонхтой гэа мэт олон давуу талуудтай", "sections": [{"title": "", "items": ["Нэг гараар эвхэх хялбар шийдэл", "Бүтэн хэвтэнэ", "0-4 нас", "4-н дугуйн дээрээ амартизатор", "Хөлийн хучлага", "Агааржуулах торон цонх", "Хүүхдийн хамгаалах бариулыг салгах боломжтой", "Утасаа хийх цахилгаантай халаастай"]}], "paragraphs": ["Нэг гараар эвхэгдэх боломжтой тул ашиглахад маш хялбар мөн хөлийн хучлагатай, амаржинтай, агаарын солилцоо нэвтрүүлэх торон цонхтой гэа мэт олон давуу талуудтай."], "images": ["/products/gallery/light-stroller-0-4-1.jpg", "/products/gallery/light-stroller-0-4-2.jpg", "/products/gallery/light-stroller-0-4-3.jpg", "/products/gallery/light-stroller-0-4-4.jpg", "/products/gallery/light-stroller-0-4-5.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/699570"},
  {"slug": "carseat-b", "storeId": "212820/683204", "title": "Машины суудал, 0-12 нас", "name": "Машины суудал", "group": "carseat", "category": "car-seats", "age": "0-12 нас", "color": "", "price": "339,000₮", "badge": "", "featured": false, "swatches": ["#8a8a8a"], "code": "G406GREY", "short": "0-12 нас хүртэл хэрэглэх боломжтой", "sections": [{"title": "Давуу талууд", "items": ["🧡0-12 нас хүртэл хэрэглэх боломжтой", "🧡Нярайн зөөлөвчтэй", "🧡Аюулгүйн бүстэй", "🧡360 градус эргэдэг тул ашиглахад хялбар", "🧡ISOFIX бэхэлгээний систем", "🧡Суудлын араас бэхлэгч", "🧡Сууудлын бүсээр давхар бэхлэх боломжтой", "🧡Тав тухтай", "🧡Аюулгүй"]}], "paragraphs": [], "images": ["/products/gallery/carseat-b-1.jpg"], "storeUrl": "https://bolorhonkids.mn/products/212820/683204"},
  {"slug": "carseat-c", "storeId": "212820/680595", "title": "Машины суудал, 0-12 нас", "name": "Машины суудал", "group": "carseat", "category": "car-seats", "age": "0-12 нас", "color": "", "price": "339,000₮", "badge": "", "featured": false, "swatches": ["#1c1c1c"], "code": "G406BLACK", "short": "0-12 нас хүртэл хэрэглэх боломжтой", "sections": [{"title": "Давуу талууд", "items": ["🧡0-12 нас хүртэл хэрэглэх боломжтой", "🧡Нярайн зөөлөвчтэй", "🧡Аюулгүйн бүстэй", "🧡360 градус эргэдэг тул ашиглахад хялбар", "🧡ISOFIX бэхэлгээний систем", "🧡Суудлын араас бэхлэгч", "🧡Сууудлын бүсээр давхар бэхлэх боломжтой", "🧡Тав тухтай", "🧡Аюулгүй"]}], "paragraphs": [], "images": ["/products/gallery/carseat-c-1.jpg"], "storeUrl": "https://bolorhonkids.mn/products/212820/680595"},
  {"slug": "travel-stroller", "storeId": "116291/673813", "title": "Аялалын тэрэг, 6сар+", "name": "Аялалын тэрэг", "group": "light", "category": "strollers", "age": "6 сар+", "color": "", "price": "379,000₮", "badge": "", "featured": false, "swatches": ["#1c1c1c"], "code": "", "short": "Аялал зугаалга мөн онгцонд авч явахад тохиромжтой хамгийн хөнгөн мөн жижиг болж эвхэгддэг тэрэг", "sections": [{"title": "", "items": ["5.7кг жинтэй", "UPF50+ нарны хаалт", "Давхар дугуйтай мөн 4-н дугуйн дээрээ амартизатортой", "Эвхээд цүнхэндээ хийгээд үүрээд явах боломжтой", "6сар-3нас"]}], "paragraphs": ["Аялал зугаалга мөн онгцонд авч явахад тохиромжтой хамгийн хөнгөн мөн жижиг болж эвхэгддэг тэрэг"], "images": ["/products/gallery/travel-stroller-1.jpg", "/products/gallery/travel-stroller-2.jpg", "/products/gallery/travel-stroller-3.jpg"], "storeUrl": "https://bolorhonkids.mn/products/116291/673813"},
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getVariants(product: Product): Product[] {
  return products.filter((p) => p.name === product.name && p.group === product.group);
}

export function getRelated(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.category === product.category && p.slug !== product.slug && p.name !== product.name)
    .slice(0, limit);
}
